#!/usr/bin/env ksh

# Control Functions
# =================
    
# Prints backtrace info  
# filename:lineno:function
# backtrace level
function backtrace {      
    local exitcode=$?
    local xtrace=$(set +o | grep xtrace)
    set +o xtrace

    local level=$1
    local deep=$((${#BASH_SOURCE[@]} - 1))
    echo "[Call Trace]"
    while [ $level -le $deep ]; do
        echo "${BASH_SOURCE[$deep]}:${BASH_LINENO[$deep-1]}:${FUNCNAME[$deep-1]}"
        deep=$((deep - 1))
    done
    $xtrace
    return $exitcode
}  

# Prints line number and "message" in error format
# err $LINENO "message"
function err {
    local exitcode=$?
    local xtrace=$(set +o | grep xtrace)
    set +o xtrace
    local msg="[ERROR] ${BASH_SOURCE[2]}:$1 $2"
    echo $msg 1>&2;
    if [[ -n ${LOGDIR} ]]; then 
        echo $msg >> "${LOGDIR}/error.log"
    fi   
    $xtrace
    return $exitcode
}

# Prints line number and "message" in warning format
# info $LINENO "message"                
function info {                         
    local exitcode=$?                   
    local xtrace=$(set +o | grep xtrace)
    set +o xtrace                       
    local msg="[INFOING] ${BASH_SOURCE[1]}:$1 $2"
    echo $msg
    $xtrace
    return $exitcode
} 

# Prints line number and "message" in warning format
# warn $LINENO "message"                
function warn {                         
    local exitcode=$?                   
    local xtrace=$(set +o | grep xtrace)
    set +o xtrace                       
    local msg="[WARNING] ${BASH_SOURCE[1]}:$1 $2"
    echo $msg
    $xtrace
    return $exitcode
} 

# Prints line number and "message" then exits
# die $LINENO "message"
function die {                          
    local exitcode=$?
    set +o xtrace
    local line=$1; shift                
    if [ $exitcode == 0 ]; then
        exitcode=1
    fi
    backtrace 2
    err $line "$*"
    # Give buffers a second to flush    
    sleep 1
    exit $exitcode
} 

