#!/usr/bin/expect

set ipaddr [lindex $argv 0]
set user [lindex $argv 1]
set keyfile [lindex $argv 2]

set DATE [exec date "+%Y%m%d%H%M%S"]  

set timeout 10

spawn ssh -i ${keyfile} ${user}@${ipaddr}

expect {
			 "*(yes/no)*"	{send "yes\r"}
			 "*assword:*"	{send "\r"}
}

expect {
			 "*assword:*"	{send "\r"}
			 "*$*"		{send "\r"}
			 "*#*"		{send "\r"}
			 "*>*"	{send "\r"}
}

expect {
			"*$*"		{send "exit\r"}
			"*#*"		{send "exit\r"}
			"*>*"		{send "exit\r"}
}

expect eof
